import type { DbThemeSection, MockDbData } from "./schema";

/** Default homepage theme document — matches the pre-theme hardcoded homepage. */
const defaultHomeSections: DbThemeSection[] = [
  { id: "sec_hero", type: "hero_carousel", settings: {} },
  { id: "sec_story", type: "rich_text", settings: {} },
  { id: "sec_testimonials", type: "testimonials", settings: {} },
  {
    id: "sec_cta",
    type: "cta_banner",
    settings: { heading: "Ready to start your wishlist?" },
  },
];

/**
 * Seed state for the mock DB. One demo couple account:
 *   email: asha@demo.grifto.in  /  password: password123
 */
export const seedData: MockDbData = {
  settings: { withdrawalFeeBps: 200, contributionFeeBps: 0 },
  theme: {
    draft: { sections: structuredClone(defaultHomeSections) },
    draftUpdatedAt: "2026-05-01T10:00:00.000Z",
    published: { sections: structuredClone(defaultHomeSections) },
    versions: [
      {
        id: "thv_1",
        version: 1,
        label: "Initial homepage",
        publishedAt: "2026-05-01T10:00:00.000Z",
        document: { sections: structuredClone(defaultHomeSections) },
      },
    ],
  },
  cmsEntries: [
    {
      id: "cms_t1",
      kind: "testimonial",
      title: "Priya & Arjun",
      body: "Our guests loved contributing to gifts we actually wanted. The QR code on our invitation made it effortless.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 0,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_t2",
      kind: "testimonial",
      title: "Sneha & Vikram",
      body: "We funded our honeymoon espresso machine in three days. Watching the progress bar fill up was so much fun!",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 1,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_t3",
      kind: "testimonial",
      title: "Meera & Karan",
      body: "Withdrawing our gift funds was simple and transparent. Grifto made our wedding easier.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 2,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_f1",
      kind: "faq",
      title: "How do guests contribute to a gift?",
      body: "Guests open your shared wishlist link or scan your QR code, choose a gift, and contribute any amount through our secure payment flow.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 0,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_f2",
      kind: "faq",
      title: "Where does the money go?",
      body: "Contributions are credited to your Grifto wallet. You can withdraw the balance to your bank account whenever you like.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 1,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_f3",
      kind: "faq",
      title: "Do guests need an account?",
      body: "No. Guests only share their name and email so you know who contributed.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 2,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_f4",
      kind: "faq",
      title: "What if a guest wants to bring a physical gift?",
      body: "Guests can reserve an item — it is marked as booked so nobody else funds it.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: null,
      ctaHref: null,
      published: true,
      sortOrder: 3,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_b1",
      kind: "banner",
      title: "Gift what they truly want",
      body: "Create your wedding wishlist, share it with a link or QR code, and let your guests contribute to gifts that matter.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: "Create your wishlist",
      ctaHref: "/register",
      published: true,
      sortOrder: 0,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_b2",
      kind: "banner",
      title: "Every rupee lands in your wallet",
      body: "Contributions are credited instantly. Withdraw to your bank account whenever you like — simple and transparent.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: "How it works",
      ctaHref: "/about",
      published: true,
      sortOrder: 1,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "cms_b3",
      kind: "banner",
      title: "Share with a link or QR code",
      body: "Put the QR on your invitation card. Guests contribute, reserve, or send a gift after the big day — no account needed.",
      imageUrl: null,
      mobileImageUrl: null,
      ctaLabel: "See a live wishlist",
      ctaHref: "/w/asha-rohan-2026",
      published: true,
      sortOrder: 2,
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
  ],
  media: [],
  users: [
    {
      id: "usr_asha",
      email: "asha@demo.grifto.in",
      phone: "9876543210",
      passwordPlain: "password123",
      firstName: "Asha",
      lastName: "Sharma",
      roleType: "bride",
      weddingDate: "2026-12-06",
      partnerName: "Rohan",
      weddingVenue: "The Leela Palace, Udaipur",
      weddingMessage:
        "We are so excited to celebrate our big day with you! Your presence is the greatest gift — but if you'd like to spoil us, here's our wishlist.",
      createdAt: "2026-06-01T10:00:00.000Z",
    },
    {
      id: "usr_rohan",
      email: "rohan@demo.grifto.in",
      phone: "9876543210",
      passwordPlain: "password123",
      firstName: "Rohan",
      lastName: "Kumar",
      roleType: "groom",
      weddingDate: "2026-12-06",
      partnerName: "Asha",
      weddingVenue: "The Leela Palace, Jaipur",
      weddingMessage:
        "We are so excited to celebrate our big day with you! Your presence is the greatest gift — but if you'd like to spoil us, here's our wishlist.",
      createdAt: "2026-06-01T10:00:00.000Z",
    },
  ],
  sessions: [],
  wishlists: [
    {
      id: "wl_asha",
      userId: "usr_asha",
      title: "Asha's Wedding Wishlist",
      shareSlug: "asha-rohan-2026",
      createdAt: "2026-06-01T10:05:00.000Z",
    },
  ],
  wishlistItems: [
    {
      id: "itm_mixer",
      wishlistId: "wl_asha",
      source: "manual",
      productId: null,
      title: "KitchenAid Stand Mixer",
      imageUrl: null,
      productUrl: null,
      priceMinor: 4599900,
      fundedMinor: 1500000,
      status: "partially_funded",
      sortOrder: 0,
      createdAt: "2026-06-02T09:00:00.000Z",
    },
    {
      id: "itm_dinnerset",
      wishlistId: "wl_asha",
      source: "url",
      productId: null,
      title: "Ceramic Dinner Set (24 pieces)",
      imageUrl: null,
      productUrl: "https://example.com/products/ceramic-dinner-set",
      priceMinor: 899900,
      fundedMinor: 899900,
      status: "fully_funded",
      sortOrder: 1,
      createdAt: "2026-06-02T09:10:00.000Z",
    },
    {
      id: "itm_espresso",
      wishlistId: "wl_asha",
      source: "manual",
      productId: null,
      title: "Espresso Machine",
      imageUrl: null,
      productUrl: null,
      priceMinor: 2499900,
      fundedMinor: 0,
      status: "open",
      sortOrder: 2,
      createdAt: "2026-06-02T09:20:00.000Z",
    },
  ],
  categories: [
    { id: "cat_home", name: "Home & Kitchen", slug: "home-kitchen" },
    { id: "cat_electronics", name: "Electronics", slug: "electronics" },
    { id: "cat_travel", name: "Travel & Experiences", slug: "travel" },
    { id: "cat_jewelry", name: "Jewelry", slug: "jewelry" },
  ],
  products: [
    { id: "prd_airfryer", categoryId: "cat_home", title: "Philips Air Fryer XL", description: "Healthy frying for the new kitchen.", imageUrl: null, priceMinor: 1299900 },
    { id: "prd_dyson", categoryId: "cat_home", title: "Dyson V12 Vacuum", description: "Cordless vacuum cleaner.", imageUrl: null, priceMinor: 4599900 },
    { id: "prd_cookware", categoryId: "cat_home", title: "Cast Iron Cookware Set", description: "5-piece premium cookware set.", imageUrl: null, priceMinor: 1899900 },
    { id: "prd_tv", categoryId: "cat_electronics", title: 'Samsung 55" QLED TV', description: "4K smart television.", imageUrl: null, priceMinor: 6499900 },
    { id: "prd_soundbar", categoryId: "cat_electronics", title: "Sonos Beam Soundbar", description: "Compact smart soundbar.", imageUrl: null, priceMinor: 3999900 },
    { id: "prd_camera", categoryId: "cat_electronics", title: "Fujifilm Instax Camera", description: "Instant camera for memories.", imageUrl: null, priceMinor: 899900 },
    { id: "prd_maldives", categoryId: "cat_travel", title: "Maldives Honeymoon Fund", description: "3 nights water villa experience.", imageUrl: null, priceMinor: 15000000 },
    { id: "prd_spa", categoryId: "cat_travel", title: "Couple Spa Day", description: "Full-day luxury spa experience.", imageUrl: null, priceMinor: 1500000 },
    { id: "prd_necklace", categoryId: "cat_jewelry", title: "Gold Pendant Necklace", description: "22k gold pendant.", imageUrl: null, priceMinor: 5499900 },
    { id: "prd_watch", categoryId: "cat_jewelry", title: "Titan Couple Watches", description: "Matching watch set.", imageUrl: null, priceMinor: 2499900 },
  ],
  guests: [
    { id: "gst_ravi", fullName: "Ravi Patel", email: "ravi@example.com", createdAt: "2026-06-10T12:00:00.000Z" },
    { id: "gst_neha", fullName: "Neha Gupta", email: "neha@example.com", createdAt: "2026-06-11T15:30:00.000Z" },
  ],
  contributions: [
    {
      id: "ctb_1",
      itemId: "itm_mixer",
      wishlistId: "wl_asha",
      guestId: "gst_ravi",
      amountMinor: 1000000,
      status: "paid",
      gatewayPaymentId: "fakepay_seed_1",
      idempotencyKey: "seed-ctb-1",
      createdAt: "2026-06-10T12:05:00.000Z",
    },
    {
      id: "ctb_2",
      itemId: "itm_mixer",
      wishlistId: "wl_asha",
      guestId: "gst_neha",
      amountMinor: 500000,
      status: "paid",
      gatewayPaymentId: "fakepay_seed_2",
      idempotencyKey: "seed-ctb-2",
      createdAt: "2026-06-11T15:35:00.000Z",
    },
    {
      id: "ctb_3",
      itemId: "itm_dinnerset",
      wishlistId: "wl_asha",
      guestId: "gst_ravi",
      amountMinor: 899900,
      status: "paid",
      gatewayPaymentId: "fakepay_seed_3",
      idempotencyKey: "seed-ctb-3",
      createdAt: "2026-06-12T10:00:00.000Z",
    },
  ],
  reservations: [],
  giftMessages: [],
  addressRequests: [],
  notifications: [
    {
      id: "ntf_1",
      userId: "usr_asha",
      type: "contribution_received",
      title: "New contribution!",
      body: "Ravi Patel contributed ₹10,000 towards KitchenAid Stand Mixer.",
      readAt: null,
      createdAt: "2026-06-10T12:05:00.000Z",
    },
    {
      id: "ntf_2",
      userId: "usr_asha",
      type: "item_fully_funded",
      title: "Gift fully funded 🎉",
      body: "Ceramic Dinner Set (24 pieces) is now fully funded.",
      readAt: "2026-06-12T18:00:00.000Z",
      createdAt: "2026-06-12T10:00:00.000Z",
    },
  ],
  ledgerEntries: [
    {
      id: "led_1",
      userId: "usr_asha",
      direction: "credit",
      amountMinor: 1000000,
      entryType: "contribution_credit",
      referenceType: "contribution",
      referenceId: "ctb_1",
      description: "Contribution from Ravi Patel — KitchenAid Stand Mixer",
      createdAt: "2026-06-10T12:05:00.000Z",
    },
    {
      id: "led_2",
      userId: "usr_asha",
      direction: "credit",
      amountMinor: 500000,
      entryType: "contribution_credit",
      referenceType: "contribution",
      referenceId: "ctb_2",
      description: "Contribution from Neha Gupta — KitchenAid Stand Mixer",
      createdAt: "2026-06-11T15:35:00.000Z",
    },
    {
      id: "led_3",
      userId: "usr_asha",
      direction: "credit",
      amountMinor: 899900,
      entryType: "contribution_credit",
      referenceType: "contribution",
      referenceId: "ctb_3",
      description: "Contribution from Ravi Patel — Ceramic Dinner Set",
      createdAt: "2026-06-12T10:00:00.000Z",
    },
    {
      id: "led_4",
      userId: "usr_asha",
      direction: "debit",
      amountMinor: 500000,
      entryType: "withdrawal_hold",
      referenceType: "withdrawal",
      referenceId: "wdr_1",
      description: "Withdrawal to bank account ····3210",
      createdAt: "2026-06-15T09:00:00.000Z",
    },
  ],
  withdrawals: [
    {
      id: "wdr_1",
      userId: "usr_asha",
      amountMinor: 500000,
      feeMinor: 10000,
      status: "completed",
      accountHolder: "Asha Sharma",
      accountNumberLast4: "3210",
      ifsc: "HDFC0001234",
      idempotencyKey: "seed-wdr-1",
      createdAt: "2026-06-15T09:00:00.000Z",
      settledAt: "2026-06-17T14:00:00.000Z",
    },
  ],
};
